### PR TITLE
Migrate to ZIP 316

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Comment by pacu** [comment]
Oh Nice to see this progressing. I think we have to piggyback the Type-Safe Address work into this PR so we don't have flying aliased-but-yet-strings in our APIs

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/ZcashLightClientKit/compare/452eaf36fb76b3bc6bdfe55a154ddd40523e043e..da1629eb825b9b3f0d7138a5ae6c30d5dee75af7) to rebase the PR and implement the ZIP 316 migration. What remains is getting all the tests to pass that were previously passing, and ensuring the changes to the SDK's public API are correct / consistent.

**Comment by pacu** [comment]
image

Darksidewalletd tests passed

**Comment by pacu** [comment]
CI won't pass since it's not pointing to the right version of zcash-light-client-ffi

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/ZcashLightClientKit/compare/7b182f2069be78647fca40b77da22138471de06b..81341226e2a6a71a153a089555fd51cf3329b959) to fix the remaining `OfflineTests`. `DerivationTool.deriveViewingKeys(seed)` now returns UFVKs, while `DerivationTool.deriveViewingKey(spendingKey)` takes a Sapling ExtSK and returns a Sapling ExtFVK (and if we keep the API in, would eventually similarly take an Orchard spending key and return an Orchard FVK).

**Review by pacu — APPROVED** [review]

**Pull request merged**
