### PR TITLE
Rust crate updates

### LINKED ISSUE #189: Integrate with latest librustzcash crates (0.4)
As a developer, I would like to use the latest librustzcash crates in order to take advantage of all the latest refactors and changes and also pave the way for using the Data Access API

Notes:
This mainly involves just copying the changes that strad did  on the android side. TODO: add a link to the related SDK PR

### PR DESCRIPTION
**Pull request by str4d**
Closes #189.

### CODE REVIEW

**Comment by gmale** [comment]
Thanks, we literally just [made a issue for this](https://github.com/zcash/ZcashLightClientKit/issues/189) thinking we'd have to figure it out! :laughing: 

We can probably close that now and merge this! :tada:

**Comment by pacu** [comment]
@str4d I'm having troubles to compile this on rustc 1.40.0, is the assertion issue fixed on with this pr as well?

**Comment by gmale** [comment]
try `cargo clean` and  then `cargo update`, I suspect that might fix that issue.

**Comment by pacu** [comment]
@str4d I got it to build by upgrading the rust compiler to 1.46.0, but then I got into the assertion issue #177

**Review by pacu — APPROVED** [review]

**Pull request merged**
